# Generated by Django 4.2.30 on 2026-05-13 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('status', models.CharField(choices=[('unknown', 'Sin verificar'), ('active', 'Activo'), ('inactive', 'Inactivo')], default='unknown', max_length=20, verbose_name='Estado')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Código HTTP')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='Tiempo de respuesta (ms)')),
                ('last_checked', models.DateTimeField(blank=True, null=True, verbose_name='Última verificación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_urls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'URL Monitoreada',
                'verbose_name_plural': 'URLs Monitoreadas',
                'ordering': ['-created_at'],
            },
        ),
    ]
