# Generated by Django 4.2.30 on 2026-05-13 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de verificación')),
                ('status', models.CharField(max_length=20, verbose_name='Estado')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Código HTTP')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='Tiempo de respuesta (ms)')),
                ('error', models.CharField(blank=True, default='', max_length=200, verbose_name='Error')),
                ('monitored_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='monitor.monitoredurl', verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Log de verificación',
                'verbose_name_plural': 'Logs de verificación',
                'ordering': ['-checked_at'],
            },
        ),
    ]
