# Generated by Django 4.2.30 on 2026-05-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_checklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_interval_minutes', models.IntegerField(choices=[(5, 'Cada 5 minutos'), (10, 'Cada 10 minutos'), (15, 'Cada 15 minutos'), (30, 'Cada 30 minutos'), (60, 'Cada hora'), (120, 'Cada 2 horas'), (360, 'Cada 6 horas'), (720, 'Cada 12 horas'), (1440, 'Cada 24 horas')], default=60, verbose_name='Intervalo de verificación automática')),
                ('auto_check_enabled', models.BooleanField(default=False, verbose_name='Verificación automática activa')),
                ('telegram_bot_token', models.CharField(blank=True, default='', max_length=300, verbose_name='Token del bot')),
                ('telegram_chat_id', models.CharField(blank=True, default='', max_length=100, verbose_name='ID del grupo/chat')),
                ('telegram_enabled', models.BooleanField(default=False, verbose_name='Notificaciones Telegram activas')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
            },
        ),
    ]
