# Generated by Django 4.2.30 on 2026-05-13 10:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredurl',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Página pública activa'),
        ),
        migrations.AddField(
            model_name='monitoredurl',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
