# Generated by Django 4.2.30 on 2026-05-13 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitor', '0006_monitoredurl_telegram_alerted'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredurl',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='shared_urls', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios'),
        ),
    ]
