# Generated by Django 4.2.30 on 2026-05-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_migrate_user_to_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoredurl',
            name='user',
        ),
    ]
