# Generated by Django 4.2.30 on 2026-05-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_remove_user_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredurl',
            name='monitoring_enabled',
            field=models.BooleanField(default=True, verbose_name='Chequeo activo'),
        ),
    ]
